name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Welcome to Actions"
      - name: Clone Repo
        uses: checkout@v3
