name: First Workflow
on: 
  push:
    branches: [ main ]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Welcome to Actions"
      - name: Clone Repo
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Build with Maven
        run: mvn -B package
      - name: Run Tests
        run: mvn -B test